global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kafka-connect-4.1.0"
    static_configs:
      - targets: ["connect:9404"]
  - job_name: "kafka-connect-4.1.1"
    static_configs:
      - targets: ["kafka-connect:9405"]
